eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: 123456
    url: jdbc:mysql://39.107.247.23:3306/shirojwt?characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: true
env: test232
